/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Genre = { 'documentary' : null } |
  { 'comedy' : null } |
  { 'drama' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'isOriginal' : boolean,
  'description' : [] | [string],
  'genre' : Genre,
  'youtubeVideoId' : string,
  'youtubeUrl' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createVideo' : ActorMethod<
    [string, [] | [string], string, Genre, boolean],
    bigint
  >,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOriginalShows' : ActorMethod<[], Array<Video>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[bigint], [] | [Video]>,
  'getVideosByGenre' : ActorMethod<[Genre], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listVideos' : ActorMethod<[], Array<Video>>,
  'loginAsAdmin' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateVideo' : ActorMethod<
    [bigint, string, [] | [string], string, Genre, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];