/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Genre = IDL.Variant({
  'documentary' : IDL.Null,
  'comedy' : IDL.Null,
  'drama' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'isOriginal' : IDL.Bool,
  'description' : IDL.Opt(IDL.Text),
  'genre' : Genre,
  'youtubeVideoId' : IDL.Text,
  'youtubeUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVideo' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, Genre, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOriginalShows' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
  'getVideosByGenre' : IDL.Func([Genre], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'loginAsAdmin' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateVideo' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, Genre, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Genre = IDL.Variant({
    'documentary' : IDL.Null,
    'comedy' : IDL.Null,
    'drama' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'isOriginal' : IDL.Bool,
    'description' : IDL.Opt(IDL.Text),
    'genre' : Genre,
    'youtubeVideoId' : IDL.Text,
    'youtubeUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, Genre, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOriginalShows' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
    'getVideosByGenre' : IDL.Func([Genre], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'loginAsAdmin' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateVideo' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, Genre, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };